version: '3'
services:
 auth-app:
  image: auth-app
  command: >
   /bin/bash -c "
   sleep 15; "
  build: LoanAuthService/
  restart: always
  network_mode: host
  ports:
  - 8080:8080
  expose:
  - 8080
  depends_on:
  - loan-mysql
 
 loan-app:
   image: loan-app
   command: >
    /bin/bash -c "
    sleep 15; "
   build: LoanService/
   restart: always
   network_mode: host
   ports:
   - 8085:8085
   expose:
   - 8085
   depends_on:
   - loan-mysql

 loan-mysql:
  image: mysql:5.6
  ports:
   - 3306:3306
  network_mode: host
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: LoanDB
   MYSQL_USER: root
   MYSQL_PASSWORD: root

 angular:
  image: angular-app
  build: LoanFrontend
  network_mode: host
  container_name: angular-docker
  ports:
   - 4200:4200
